_target_: src.datamodules.intelimage_datamodule.IntelImgClfDataModule
root_data_dir: ${paths.data_dir}
train_data_dir: null
test_data_dir: null
val_data_dir: null
batch_size: 64
num_workers: 8
pin_memory: False
